gem:
  build: .
  command: guard -p
  volumes:
    - .:/usr/src/app
  volumes_from:
    - bundle

bundle:
  image: rspecapib_gem
  command: echo "I'm a little data container, short and stout..."
  volumes:
    - /usr/local/bundle
